### PR TITLE
Exit with proper exit codes

### LINKED ISSUE #1: Enhancement: Exit with an exit code other than 0 if validation fails
Hej,

this enhancement is crucial for running this CLI in an CI environment.
Would you accept a PR for this?

Cheers, Michael

### PR DESCRIPTION
**Pull request by mischah**
Here you are :octocat: 

## Before
before

## After 
after

---
Closes #1

### CODE REVIEW

**Comment by dutchenkoOleg** [comment]
Nice and clear, 
@mischah thx for PR

**Comment by mischah** [comment]
Thanks for the merge.

Will you release that pretty soon? Or are there other changes that should end up in the next release?

**Comment by dutchenkoOleg** [comment]
@mischah just published 
https://github.com/dutchenkoOleg/node-w3c-validator/releases  
and https://www.npmjs.com/package/node-w3c-validator

**Comment by mischah** [comment]
Nice. Thanks 💖

**Pull request merged**
